[config]
# Set this to `false` to run the tasks at workspace root directory and not on the members
default_to_workspace = false
# Set this to `true` to avoid clashes with core commands (e.g. `cargo make publish` vs `cargo publish`)
skip_core_tasks = true

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.test]
command = "cargo"
args = ["test", "--locked"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--tests", "--", "-D", "warnings"]

# This task requires the `cargo-contract` package: https://crates.io/crates/cargo-contract
[tasks.release]
script = """
contracts=(
  contract-name
)

for contract in ${contracts[@]}; do
  cd project-name/contracts/$contract &&
  cargo contract build --release --manifest-path ./Cargo.toml
done
"""

# This task requires the `cargo-contract` package: https://crates.io/crates/cargo-contract
[tasks.debug]
script = """
contracts=(
  contract-name
)

for contract in ${contracts[@]}; do
  cd project-name/contracts/$contract &&
  cargo contract build --manifest-path ./Cargo.toml
done
"""

# This task requires the `cargo-udeps` package: https://crates.io/crates/cargo-udeps
[tasks.udeps]
toolchain = "nightly"
command = "cargo"
args = ["udeps"]

# This task requires the `cargo-contract` package: https://crates.io/crates/cargo-contract
[tasks.check]
command = "cargo"
args = [
  "contract",
  "check",
]

# Update the `crates` array in the script to reflect the content of your project
[tasks.publish]
script = """
crates=(
  crate
)

for crate in ${crates[@]}; do
  cargo publish -p $crate
  echo "💤 sleeping for 30 sec before publishing the next crate..."
  sleep 30
done
"""
